config/routes.rb
get 'projects/:id/lookouts', :to => 'lookouts#index', :as => 'lookouts'
get 'projects/:id/popups/time_issue', :to => 'popups#time_issue'
get 'projects/:id/popups/time_user', :to => 'popups#time_user' , :as => 'timeuser'

match 'shared/issues', :controller => 'issues_api', :action => 'index', :via => [:get]

app/controllers/issues_api_controller.rb
class IssuesApiController < ApplicationController
  helper :custom_fields
  include QueriesHelper

  def index
    retrieve_query
      respond_to do |format|
        format.api  {
          @offset, @limit = api_offset_and_limit
          @query.column_names = %w(author)
          @issue_count = @query.issue_count
          @issues = @query.issues(:offset => @offset, :limit => @limit)
          Issue.load_visible_relations(@issues) if include_in_api_response?('relations')
        }
      end
  end
end

#Redmine apilerini direk kullanmak yerine özelleştirdim
#gereksiz alanları sildim, spent_hours ve total_spent_hours gibi alanları çektim
#bunun bize iki tane faydası vardır
#birincisi görsel grafik oluştururken popup için başka json isteği yapmayacağız
#ikincisi ise issues.json gibi isteklerden daha hızlı işlem yapacağız

app/controllers/lookouts_controller.rb
class LookoutsController < ApplicationController
  before_filter :find_project, :authorize, :only => :index

  def index
    ###controller ve helpers arasında bir çok kez veri alışverisi yaptım
    @page_current= params[:page]    # page index al ==> lookouts?page=2&query=sort=category:asc
    path = params[:query]           # path(sorgu) index al ==> sort=category:asc,sort=category:desc
    @per_page= params[:per_page]    #(1-50/75) Sayfa başına: 25, 50, 100 gösterimi için şeçileni bul

    @orderQuery = path    #değişkeni helperde kullanmak için @ ile tanımladım
    if !path.blank? #Eğer sayfa yüklendiğinde path değişkeni boş değilse projenin adrresini ve path değişkenini request_query'e ekle
      request_query = "/shared/issues.json?project_id="+ @project.id.to_s  + path.to_s
    else
      request_query = "/shared/issues.json?project_id="+ @project.id.to_s
    end

    #PAGINATE
      #eğer paginate linklerinden [1,2,3,4] herhangi birine tıklamışsa
    if @page_current
      request_query = request_query + "&page=" + @page_current
    end

      #eğer per_page linklerinden herhangi birine tıklamışsa
    if @per_page
      request_query = request_query + "&limit=" + @per_page
    end

    @issue_count = Issue.where(project_id: @project.id.to_s).all.count

    @issue_pages = Paginator.new @issue_count, per_page_option, @page_current
    #PAGINATE END

    #parametrelerle oluşturulan adresin son hali (Vue.js'in json isteği yapması için oluşturuldu.)
    @url = "#{request.base_url}#{request_query}"

  end

  #hangi projede olduğunu bul
  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/popups_controller.rb
class PopupsController < ApplicationController
  before_action :only => [:time_issue, :time_user]
  #time_issue.html.erb ve _time_issue.html.erb olarak iki sayfa oluşturdum
  # _ taglı sayfa js isteğine yanıt verecek
  def time_issue
    @done_ratio = params[:dr]
    @estimated_hours = params[:eh]
    @spent_hours = params[:sh]
    @subject = params[:subject]

    respond_to do |format|
      format.html
      format.js  #eğer popup olarak gösterecekse js isteği yap
    end
  end

  def time_user
    @project_id= Project.find(params[:id]).id

    @records_user=TimeEntry.select("concat(users.firstname,' ',users.lastname) AS namesurname ,SUM(hours) AS totalhours")
                  .joins("INNER JOIN users ON users.id=time_entries.user_id WHERE time_entries.project_id=#{@project_id}")
                    .group("namesurname")


    @records_category=TimeEntry.select("(SELECT name FROM issue_categories WHERE issues.category_id=issue_categories.id) AS issueCatName, SUM(time_entries.hours) AS totalhours")
                  .joins("INNER JOIN issues ON issues.id=time_entries.issue_id WHERE time_entries.project_id=#{@project_id}")
                    .group("issueCatName")

    respond_to do |format|
      format.html
    end
  end

end

app/helpers/lookouts_helper.rb
module LookoutsHelper

  def column_header(column, options={})

    #normalde bu tarz dizileri içeren veriler model dosyası fonksiyonlarına erişerek veritabanından çekilmedir
    #ancak ben bu bir plugin olduğundan veri tabanına yeni alan eklemekten çekindiğim için dizide tutmayı tercih ettim
    arr= ["&sort=id:asc",
          "&sort=id:desc",
          "&sort=category:asc",
          "&sort=category:desc",
          "&sort=author:asc",
          "&sort=author:desc"]

    css,order = nil
    case column
    when '#'
      if @orderQuery == arr[0]
        css = 'sort asc'
        order = arr[1]
      else
        css = 'sort desc'
        order = arr[0]
      end
    when 'Category'
      if @orderQuery == arr[2]
        css = 'sort asc'
        order = arr[3]
      else
        css = 'sort desc'
        order = arr[2]
      end
    else
      if @orderQuery == arr[4]
        css = 'sort asc'
        order = arr[5]
      else
        css = 'sort desc'
        order = arr[4]
      end
    end
    link_options = {
        :class => css
      }
    content = link_to(
        column,
        { :page  => @issue_pages.page,
          :query  => order},
        link_options
      )
    content_tag('th', content)
  end


end

app/views/lookouts/_table.html.erb
<!--asc desc sorgu yapabilmek için kullanılacak link
    lookouts controller index methoduna :query den gelecek olan syntaxı yollar
    query_syntax methodu lookouts_helper içerisindedir
-->

<table class="list issues" id="listIssues">
  <thead>
    <tr class="lookouts-table-top">
        <%= column_header("#") %>
        <th><%=l(:field_status) %></th>
        <th><%=l(:field_subject) %></th>
        <%= column_header(l(:field_category)) %>
        <%= column_header(l(:field_author)) %>
        <th><%=l(:label_spent_time) %></th>
    </tr>
  </thead>
  <tbody>
    <tr v-for="issue in info.issues" v-bind:id="'issue-' + issue.id" >
      <td id="id" class="id"><a v-bind:href="'/issues/' + issue.id">{{ issue.id }}</a></td>
      <td class="status">{{ issue.status.name }}</td>
      <td class="subject"><a v-bind:href="'popups/time_issue?issue_id=' + issue.id+'&dr='+issue.done_ratio
        +'&eh='+issue.estimated_hours+'&sh='+issue.spent_hours
        +'&subject='+issue.subject"
        data-remote="true">{{ issue.subject }}</a>
      </td>
      <td class="category"><span v-if="issue.category"> {{ issue.category.name }}</span></td>
      <td class="author"><a v-bind:href="'/users/' + issue.author.id">{{ issue.author.name }}</a></td>
      <td class="spent-time attribute"><span v-if="issue.spent_hours"> {{ issue.spent_hours }} <%=l(:label_hours) %> </span></td>
    </tr>
  </tbody>
  <div id="ajax-modal" style="display:none;"></div><!--Popup modal penceresini div -->
</table>

app/views/lookouts/index.html.erb
<!--vue js kullanabilmek için gerekli script dosyaları
    axios.js redmine api linklerini kullanmayı sağlar
-->
<%= javascript_include_tag('vue', :plugin => 'lookouts') %>
<%= javascript_include_tag('axios.min', :plugin => 'lookouts') %>
<%= javascript_include_tag('lodash.min', :plugin => 'lookouts') %>

<!--Bu iki javascript dosyası aslında Popups views lerine ait
ancak popups sayfasını js isteği ile çağırdığımız için ilk seferde modal penceresini açmıyor
o yüzden listIssues de yüklemem gerekiyordu ancak bu listenin yüklenirken daha fazla milisaniyede
açılmasına sebeb oluyor-->
<script src="//www.google.com/jsapi"> </script>
<%= javascript_include_tag('chartkick.min', :plugin => 'lookouts') %>


<h2><%=l(:label_plugin_plural) %></h2>
<!--hr cizgisi -->
<fieldset class="collapsible collapsed"></fieldset>

<!--lookouts_style isimli css dosyasını yükle -->
<%= stylesheet_link_tag('lookouts_style', :plugin => 'lookouts') %>

<%= render :partial => 'lookouts/table' %>
<span class="pagination"><%= pagination_links_full @issue_pages, @issue_count %></span>


<% content_for :sidebar do %>
    <%= render :partial => 'shared/sidebar' %>
    <h3><%= l(:label_all_project_time) %></h3>
    <%= link_to l(:label_all_project_time_detail), timeuser_path %>
<% end %>

<script>
  var listIssues = new Vue({
     el: '#listIssues',
     data () {
       return {
         info: [],  //tüm json verinin tutulduğu dizi
         loading: true,
         errored: false // json veri hatalıysa uyarı
       }
     },

     mounted() {  // methodların çağırıldığı yer
        this.getData();
     },

     methods: {
       getData() {
         axios
           .get('<%=@url%>') // vue.js içerisindeki bu rails değişkeni controller tarafından oluşturulup gönderilen json url linkidir.
           .then(response => {
             this.info = response.data; // yanıt varsa bilgileri taşı
             console.log('Redmine Lookout plugin developed by Mehmet Yılmaz')
           })
           .catch(error => {
             console.log(error) // yanıt yoksa hataları ayarla
             this.errored = true
           })
           .finally(() => this.loading = false)
          }
     },
   })
</script>

app/views/popups/_time_issue.html.erb
<div id="time_issue_modal">
  <!--MODAL ICIN-->
   <%= stylesheet_link_tag('lookouts_style', :plugin => 'lookouts') %>

   <table class="time_issue_modal_content" >
     <tr>
       <td><h2><%=l(:field_done_ratio) %></h2><hr class="style-hr"/></td>
       <td><h2><%=l(:label_chart_percent_time_issue) %> ( <%=l(:field_hours) %> )</h2><hr class="style-hr"/></td>
     </tr>
     <tr>
       <td>
        <% if @done_ratio == 'undefined' %><br>
           <div class="alert alert-warning" role="alert">
             <%=l(:label_no_data) %>
           </div>
        <% else %>
          <div id="donut" style="width: 430px;"></div>
            <script>
               new Chartkick.PieChart("donut", [["<%=l(:label_chart_percent_finish) %> ",<%= @done_ratio %>],["<%=l(:label_chart_percent_remain) %>",100 - <%= @done_ratio %>]], {"colors": ["#3366CC", "#00b300"]}, {donut: "true"});
            </script>

        <% end %>
       </td>
       <td>
        <% if ((@spent_hours == 'undefined') && (@estimated_hours == 'undefined'))  %><br>
          <div class="alert alert-warning" role="alert">
            <%=l(:label_no_data) %>
          </div>
        <% else %>
          <div id="pie-label" style="width: 430px;"></div>
           <script>
              new Chartkick.PieChart("pie-label",[["<%=l(:field_estimated_hours) %>",<%= @estimated_hours %>],["<%=l(:label_spent_time) %>",<%= @spent_hours %>]], {"colors": ["#00b300", "#dc3912"]});
           </script>

        <% end %>
       </td>
     </tr>
   </table>
</div>

app/views/popups/time_issue.html.erb
<%= render :partial => 'popups/time_issue' %>

app/views/popups/time_issue.js.erb
$('#ajax-modal').html("<%= j (render 'time_issue')%>");
showModal('time_issue_modal', '890px','<%=l(:label_chart_name) %> / <%=l(:field_subject) %> : <%= @subject %>');

app/views/popups/time_user.html.erb
<%= javascript_include_tag('Chart.bundle', :plugin => 'lookouts') %>
<%= javascript_include_tag('chartkick.min', :plugin => 'lookouts') %>
<%= stylesheet_link_tag('lookouts_style', :plugin => 'lookouts') %>

<div class="spent_time box">
  <h3 class="icon icon-issue"><%=l(:label_all_project_time)%></h3>
  <table class="time_user_modal_content" >
    <tr>
      <td>
        <h3><%=l(:label_cat_time) %></h3>
        <div id="pie-category" style="height: 200px;"></div>
          <script>
              new Chartkick.PieChart("pie-category", [
                <% @records_category.each do |row| %>
                  ["<%= row.issueCatName %>",<%= row.totalhours %>],
                <% end %>
              ], {dataset: {borderWidth: 20}});
          </script>
      </td>
    </tr>
    <tr>
      <td>
        <h3><%=l(:label_user_time) %></h3>
        <div id="baruser" style="height: 200px;"></div>
          <script>
            new Chartkick.BarChart("baruser",[
            <% @records_user.each do |row| %>
              ["<%= row.namesurname %>",<%= row.totalhours %>],
            <% end %>
            ]);
          </script>
      </td>
    </tr>
  </table>
</div>


<% content_for :sidebar do %>
  <%= render :partial => 'shared/sidebar'%>
  <h3><%= l(:label_plugin_plural) %></h3>
  <%= link_to l(:label_plugin_watch), lookouts_path %>
<% end %>

app/views/shared/_sidebar.html.erb
<h3><%= l(:label_issue_plural) %></h3>
<ul>
<li><%= link_to l(:label_issue_view_all), _project_issues_path(@project, :set_filter => 1) %></li>
<% if @project %>
<li><%= link_to l(:field_summary), project_issues_report_path(@project) %></li>
<% end %>

<% if User.current.allowed_to?(:import_issues, @project, :global => true) %>
<li><%= link_to l(:button_import), new_issues_import_path %></li>
<% end %>
</ul>

<%= call_hook(:view_issues_sidebar_issues_bottom) %>
<%= call_hook(:view_issues_sidebar_planning_bottom) %>
<%= call_hook(:view_issues_sidebar_queries_bottom) %>